name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: >
          mvn --batch-mode --update-snapshots verify 
          -Plifestream -Pmy-lifeastream -Pjbake
          -Dgoodreads.mail=${{env.GOODREADS_MAIL}}
          -Dgoodreads.password=${{env.GOODREADS_PASSWORD}}
          -Dwordpress.login=${{env.WORDPRESS_LOGIN}}
          -Dwordpress.password=${{env.WORDPRESS_PASSWORD}}
          -Dwordpress.address=${{env.WORDPRESS_ADDRESS}}
          -Dtwitter4j.oauth.accessToken=${{env.TWITTER4J_OAUTH_ACCESSTOKEN}}
          -Dtwitter4j.oauth.accessTokenSecret=${{env.TWITTER4J_OAUTH_ACCESSTOKENSECRET}}
          -Dshaarli.login=${{env.SHAARLI_LOGIN}}
          -Dshaarli.password=${{env.SHAARLI_PASSWORD}}
          -Dshaarli.address=${{env.SHAARLI_ADDRESS}}
