name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v1
      - name: Obviously checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        env:
          GOODREADS_MAIL: ${{secrets.GOODREADS_MAIL}}
          GOODREADS_PASSWORD: ${{secrets.GOODREADS_PASSWORD}}
          WORDPRESS_LOGIN: ${{secrets.WORDPRESS_LOGIN}}
          WORDPRESS_PASSWORD: ${{secrets.WORDPRESS_PASSWORD}}
          WORDPRESS_ADDRESS: ${{secrets.WORDPRESS_ADDRESS}}
          TWITTER4J_OAUTH_ACCESSTOKEN: ${{secrets.TWITTER4J_OAUTH_ACCESSTOKEN}}
          TWITTER4J_OAUTH_ACCESSTOKENSECRET: ${{secrets.TWITTER4J_OAUTH_ACCESSTOKENSECRET}}
          SHAARLI_LOGIN: ${{secrets.SHAARLI_LOGIN}}
          SHAARLI_PASSWORD: ${{secrets.SHAARLI_PASSWORD}}
          SHAARLI_ADDRESS: ${{secrets.SHAARLI_ADDRESS}}
        run: >
          mvn
          -DskipTests
          -Pmy-lifestream -Pjbake -Pplugins
          -Dgoodreads.mail="$GOODREADS_MAIL"
          -Dgoodreads.password="$GOODREADS_PASSWORD"
          -Dwordpress.login="$WORDPRESS_LOGIN"
          -Dwordpress.password="$WORDPRESS_PASSWORD"
          -Dwordpress.address="$WORDPRESS_ADDRESS"
          -Dtwitter4j.oauth.accessToken="$TWITTER4J_OAUTH_ACCESSTOKEN"
          -Dtwitter4j.oauth.accessTokenSecret="$TWITTER4J_OAUTH_ACCESSTOKENSECRET"
          -Dshaarli.login="$SHAARLI_LOGIN"
          -Dshaarli.password="$SHAARLI_PASSWORD"
          -Dshaarli.address="$SHAARLI_ADDRESS"
          -Dlifestream.selenium.browser=chrome
          -Dlifestream.selenium.remote.url=http://localhost:4444/wd/hub
          --batch-mode --update-snapshots
          verify 
          -X
